version: "3.8"
services:
  solr1:
    image: solr:${SOLR_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_solr1
    ports:
     - "8981:8983"
    environment:
      - SOLR_HOST=solr1
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # custom collections \ schema
      - "./data/solr/collections/:/tmp/solr-collections/"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  solr2:
    image: solr:${SOLR_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_solr2
    ports:
     - "8982:8983"
    environment:
      - SOLR_HOST=solr2
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  solr3:
    image: solr:${SOLR_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_solr3
    ports:
     - "8983:8983"
    environment:
      - SOLR_HOST=solr3
      - ZK_HOST=zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    networks:
      - solr

  zoo1:
    image: zookeeper:${ZOO_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_zoo1
    hostname: zoo1
    ports:
      - 2181:2181
      - 7001:7000
      - 8081:8080
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo2:
    image: zookeeper:${ZOO_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_zoo2
    hostname: zoo2
    ports:
      - 2182:2181
      - 7002:7000
      - 8082:8080
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

  zoo3:
    image: zookeeper:${ZOO_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_zoo3
    hostname: zoo3
    ports:
      - 2183:2181
      - 7003:7000
      - 8083:8080
    volumes:
      # force local timezone
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    networks:
      - solr

networks:
  solr:
